In [ ]:
import pandas as pd
pd.read_csv('Iris.csv')

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [ ]:
import numpy as np 
import random
np. random. seed (0)
x1 =np.random.randint (10, size=6)
x2 = np.random. randint (10, size = (3,4))
x3 = np.random. randint(10,size =(3,4,5))
print ("x3 ndim:", x3. ndim)
print ("x3 shape ", x3.shape)
print ("X3 Size;" , x3.size)

x3 ndim: 3
x3 shape  (3, 4, 5)
X3 Size; 60


In [ ]:
import numpy as np
x = np.arange(1,10,dtype=int)
y = np.arange(11,20,dtype=int)
z = np.concatenate((x,y))
print(z)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


In [ ]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[11,12,13],[14,15,16]])
z = np.concatenate((x,y))
print(z)


[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


In [ ]:
import numpy as np
x = np.arange(1,10,dtype=int)
print("x+5 :",x+5)
x = np.arange(1,10,dtype=int)
print("x-5 :",x-5)
x = np.arange(1,10,dtype=int)
print("x/5 :",x/5)
x = np.arange(1,10,dtype=int)
print("x*5 :",x*5)
x = np.arange(1,10,dtype=int)
print("x^2 :",np.power(x,2))
x = np.arange(1,10,dtype=int)
print("x%2:",np.mod(x,2))
x = np.arange(1,10,dtype=int)
print("log(x):",np.log(x))
x = np.arange(1,10,dtype=int)
print("log2(x):",np.log2(x))
x = np.arange(1,10,dtype=int)
print("log10(x):",np.log10(x))
x = np.arange(1,10,dtype=int)
print("sin :",np.sin(x))
x = np.arange(1,10,dtype=int)
print("cos :",np.cos(x))
x = np.arange(1,10,dtype=int)
print("tan :",np.tan(x))

x+5 : [ 6  7  8  9 10 11 12 13 14]
x-5 : [-4 -3 -2 -1  0  1  2  3  4]
x/5 : [0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
x*5 : [ 5 10 15 20 25 30 35 40 45]
x^2 : [ 1  4  9 16 25 36 49 64 81]
x%2: [1 0 1 0 1 0 1 0 1]
log(x): [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
log2(x): [0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
log10(x): [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
sin : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
cos : [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
tan : [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566]
